#
# CI
#
image: cypress/base:latest

stages:
- build
- test

build-npm-dev:
  stage: build
  script:
    - npm install
    - npm run dev
  tags: 
    - build-2
  artifacts:
    paths:
      - node_modules/
  cache:
    key: ${CI_COMMIT_REF_SLUG}--npm-dev
    paths:
      - node_modules/
      - ~/.cache/

test-eslint:
  stage: test
  needs:
    - build-npm-dev
  dependencies:
    - build-npm-dev
  script:
    - npm run lint
  tags:
    - build-2

test-cypress:
  stage: test
  needs:
    - build-npm-dev
  dependencies:
    - build-npm-dev
  script:
    - npx cypress install
    - npx cypress run
    - npm stop
  tags:
    - build-2